package com.dracosoft.simplecalculator;
//DracosoftCalc 
public class SCalculatorJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SCalculatorJFrame.class.getName());

    public SCalculatorJFrame() {
        initComponents();
            setLocationRelativeTo(null);
            estiloBoton(btn_resta);
            estiloBoton(btn_division);
            estiloBoton(btn_multi);
            estiloBoton(btn_suma);
            estiloBoton(btn_c);
            estiloIgual(btn_igual);   
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_resta = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_multi = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_00 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtOperacion = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_resta.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_resta.setForeground(new java.awt.Color(102, 102, 102));
        btn_resta.setText("-");
        btn_resta.setBorder(null);
        btn_resta.setContentAreaFilled(false);
        btn_resta.setFocusPainted(false);
        btn_resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_resta.addActionListener(this::btn_restaActionPerformed);
        jPanel1.add(btn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 50, 50));

        btn_c.setBackground(new java.awt.Color(255, 255, 255));
        btn_c.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_c.setForeground(new java.awt.Color(102, 102, 102));
        btn_c.setText("C");
        btn_c.setBorder(null);
        btn_c.setContentAreaFilled(false);
        btn_c.setFocusPainted(false);
        btn_c.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_c.addActionListener(this::btn_cActionPerformed);
        jPanel1.add(btn_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, 50));

        btn_division.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_division.setForeground(new java.awt.Color(102, 102, 102));
        btn_division.setText("/");
        btn_division.setBorder(null);
        btn_division.setContentAreaFilled(false);
        btn_division.setFocusPainted(false);
        btn_division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_division.addActionListener(this::btn_divisionActionPerformed);
        jPanel1.add(btn_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 50, 50));

        btn_multi.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_multi.setForeground(new java.awt.Color(102, 102, 102));
        btn_multi.setText("X");
        btn_multi.setBorder(null);
        btn_multi.setContentAreaFilled(false);
        btn_multi.setFocusPainted(false);
        btn_multi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multi.addActionListener(this::btn_multiActionPerformed);
        jPanel1.add(btn_multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, 50));

        btn_7.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_7.setForeground(new java.awt.Color(102, 102, 102));
        btn_7.setText("7");
        btn_7.setBorder(null);
        btn_7.setContentAreaFilled(false);
        btn_7.setFocusPainted(false);
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.addActionListener(this::btn_7ActionPerformed);
        jPanel1.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 50));

        btn_8.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_8.setForeground(new java.awt.Color(102, 102, 102));
        btn_8.setText("8");
        btn_8.setBorder(null);
        btn_8.setContentAreaFilled(false);
        btn_8.setFocusPainted(false);
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.addActionListener(this::btn_8ActionPerformed);
        jPanel1.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 50, 50));

        btn_6.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_6.setForeground(new java.awt.Color(102, 102, 102));
        btn_6.setText("6");
        btn_6.setBorder(null);
        btn_6.setContentAreaFilled(false);
        btn_6.setFocusPainted(false);
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.addActionListener(this::btn_6ActionPerformed);
        jPanel1.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 50, 50));

        btn_suma.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_suma.setForeground(new java.awt.Color(102, 102, 102));
        btn_suma.setText("+");
        btn_suma.setBorder(null);
        btn_suma.setContentAreaFilled(false);
        btn_suma.setFocusPainted(false);
        btn_suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_suma.addActionListener(this::btn_sumaActionPerformed);
        jPanel1.add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 50, 50));

        btn_4.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_4.setForeground(new java.awt.Color(102, 102, 102));
        btn_4.setText("4");
        btn_4.setBorder(null);
        btn_4.setContentAreaFilled(false);
        btn_4.setFocusPainted(false);
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.addActionListener(this::btn_4ActionPerformed);
        jPanel1.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, 50));

        btn_5.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_5.setForeground(new java.awt.Color(102, 102, 102));
        btn_5.setText("5");
        btn_5.setBorder(null);
        btn_5.setContentAreaFilled(false);
        btn_5.setFocusPainted(false);
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.addActionListener(this::btn_5ActionPerformed);
        jPanel1.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 50, 50));

        btn_9.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_9.setForeground(new java.awt.Color(102, 102, 102));
        btn_9.setText("9");
        btn_9.setBorder(null);
        btn_9.setContentAreaFilled(false);
        btn_9.setFocusPainted(false);
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.addActionListener(this::btn_9ActionPerformed);
        jPanel1.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 50, 50));

        btn_1.setBackground(new java.awt.Color(153, 255, 255));
        btn_1.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_1.setForeground(new java.awt.Color(102, 102, 102));
        btn_1.setText("1");
        btn_1.setBorder(null);
        btn_1.setContentAreaFilled(false);
        btn_1.setFocusPainted(false);
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.addActionListener(this::btn_1ActionPerformed);
        jPanel1.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, 50));

        btn_2.setBackground(new java.awt.Color(153, 255, 255));
        btn_2.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_2.setForeground(new java.awt.Color(102, 102, 102));
        btn_2.setText("2");
        btn_2.setBorder(null);
        btn_2.setContentAreaFilled(false);
        btn_2.setFocusPainted(false);
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.addActionListener(this::btn_2ActionPerformed);
        jPanel1.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 50, 50));

        btn_3.setBackground(new java.awt.Color(153, 255, 255));
        btn_3.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_3.setForeground(new java.awt.Color(102, 102, 102));
        btn_3.setText("3");
        btn_3.setBorder(null);
        btn_3.setContentAreaFilled(false);
        btn_3.setFocusPainted(false);
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.addActionListener(this::btn_3ActionPerformed);
        jPanel1.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 50, 50));

        btn_igual.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_igual.setForeground(new java.awt.Color(102, 102, 102));
        btn_igual.setText("=");
        btn_igual.setBorder(null);
        btn_igual.setContentAreaFilled(false);
        btn_igual.setFocusPainted(false);
        btn_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_igual.addActionListener(this::btn_igualActionPerformed);
        jPanel1.add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 50, 40));

        btn_00.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_00.setForeground(new java.awt.Color(102, 102, 102));
        btn_00.setText("00");
        btn_00.setBorder(null);
        btn_00.setContentAreaFilled(false);
        btn_00.setFocusPainted(false);
        btn_00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_00.addActionListener(this::btn_00ActionPerformed);
        jPanel1.add(btn_00, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 50, 50));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOperacion.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(255, 255, 255));
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, 260, 30));

        txtResultado.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 260, 56));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DRACOSOFT CALCULATOR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 120));

        btn_0.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        btn_0.setForeground(new java.awt.Color(102, 102, 102));
        btn_0.setText("0");
        btn_0.setBorder(null);
        btn_0.setContentAreaFilled(false);
        btn_0.setFocusPainted(false);
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.addActionListener(this::btn_0ActionPerformed);
        jPanel1.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        addNumber("-");
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        txtOperacion.setText("");
        txtResultado.setText(" ");
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        addNumber("/");
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiActionPerformed
        addNumber("*");
    }//GEN-LAST:event_btn_multiActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        addNumber("7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        addNumber("8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        addNumber("6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        addNumber("+");
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        addNumber("4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        addNumber("5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        addNumber("9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        addNumber("1");
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        addNumber("2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        addNumber("3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
            try {
        double resultado = evaluar(txtOperacion.getText());
        txtResultado.setText(String.valueOf(resultado));
    } catch (Exception e) {
        txtResultado.setText("Error");
        }
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_00ActionPerformed
        addNumber("00");
    }//GEN-LAST:event_btn_00ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        addNumber("0");
    }//GEN-LAST:event_btn_0ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SCalculatorJFrame().setVisible(true));
    }
    
public void addNumber(String digito){
    txtOperacion.setText(txtOperacion.getText() + digito);
    
    try {
        double resultado = evaluar(txtOperacion.getText());
        txtResultado.setText(String.valueOf(resultado));
    } catch (Exception e) {
        txtResultado.setText("");
    }
}

public double evaluar(String expr) {
    final String expression = expr.replace("X", "*");

    return new Object() {
        int pos = -1, ch;

        void nextChar() {
            ch = (++pos < expression.length()) ? expression.charAt(pos) : -1;
        }

        boolean eat(int charToEat) {
            while (ch == ' ') nextChar();
            if (ch == charToEat) {
                nextChar();
                return true;
            }
            return false;
        }

        double parse() {
            nextChar();
            return parseExpression();
        }

        double parseExpression() {
            double x = parseTerm();
            while (true) {
                if (eat('+')) x += parseTerm();
                else if (eat('-')) x -= parseTerm();
                else return x;
            }
        }

        double parseTerm() {
            double x = parseFactor();
            while (true) {
                if (eat('*')) x *= parseFactor();
                else if (eat('/')) x /= parseFactor();
                else return x;
            }
        }

        double parseFactor() {
            if (eat('+')) return parseFactor();
            if (eat('-')) return -parseFactor();

            double x;
            int startPos = this.pos;

            if (eat('(')) {
                x = parseExpression();
                eat(')');
            } else if ((ch >= '0' && ch <= '9') || ch == '.') {
                while ((ch >= '0' && ch <= '9') || ch == '.') nextChar();
                x = Double.parseDouble(expression.substring(startPos, this.pos));
            } else {
                throw new RuntimeException("Error");
            }

            return x;
        }
    }.parse();
}
    
private void estiloBoton(javax.swing.JButton btn) {
    btn.setUI(new javax.swing.plaf.basic.BasicButtonUI());

    btn.setBackground(new java.awt.Color(255,102,102));
    btn.setForeground(java.awt.Color.WHITE);

    btn.setFocusPainted(false);
    btn.setContentAreaFilled(false);
    btn.setOpaque(false);

    btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));

    
 btn.setBorder(new javax.swing.border.AbstractBorder() {
    @Override
    public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                            java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

        
        g2.setColor(btn.getBackground());
        g2.fillRoundRect(0, 0, width, height, 30, 30);

        
        g2.setColor(btn.getForeground());
        java.awt.FontMetrics fm = g2.getFontMetrics();
        String text = btn.getText();

        int xText = (width - fm.stringWidth(text)) / 2;
        int yText = (height + fm.getAscent()) / 2 - 4;

        g2.drawString(text, xText, yText);
    }
});
}

private void estiloIgual(javax.swing.JButton btn) {
    btn.setUI(new javax.swing.plaf.basic.BasicButtonUI());

    btn.setBackground(new java.awt.Color(255, 255, 255)); 
    btn.setForeground(new java.awt.Color(220, 120, 130)); 

    btn.setFocusPainted(false);
    btn.setBorderPainted(false);
    btn.setContentAreaFilled(false);
    btn.setOpaque(true);

    btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 36));

    
    btn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btn.setBackground(new java.awt.Color(245, 245, 245));
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            btn.setBackground(new java.awt.Color(255, 255, 255));
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_00;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multi;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
